# Generated by Django 5.2.1 on 2025-06-03 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('vagas_disponiveis', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('documento', models.FileField(upload_to='documentos/')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVT.creche')),
            ],
        ),
        migrations.AddField(
            model_name='creche',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MVT.regiaoadministrativa'),
        ),
    ]
