# Generated by Django 5.2.1 on 2025-06-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='data_nascimento',
        ),
    ]
