# Generated by Django 5.2.2 on 2025-06-07 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0002_remove_matricula_cpf_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='documento',
        ),
        migrations.AddField(
            model_name='matricula',
            name='certidao_nascimento',
            field=models.FileField(default='documentos/certidao_padrao.pdf', upload_to='documentos/certidoes/'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='comprovante_residencia',
            field=models.FileField(default='comprovantes_residencia_P.pdf', upload_to='documentos/comprovantes_residencia/'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cpf_responsavel',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='documento_responsavel',
            field=models.FileField(default='documentos/documentos_responsavel_P.pdf', upload_to='documentos/documentos_responsavel/'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='matricula',
            name='endereco_bairro',
            field=models.CharField(default='Bairro Exemplo', max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='endereco_cidade',
            field=models.CharField(default='Cidade Exemplo', max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='endereco_numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='matricula',
            name='endereco_rua',
            field=models.CharField(default='Rua Exemplo', max_length=200),
        ),
        migrations.AddField(
            model_name='matricula',
            name='endereco_uf',
            field=models.CharField(default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='matricula',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Feminino', max_length=20),
        ),
        migrations.AddField(
            model_name='matricula',
            name='telefone',
            field=models.CharField(default='(00)00000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
