# Generated by Django 5.2.2 on 2025-06-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0003_remove_matricula_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='certidao_nascimento',
            field=models.FileField(upload_to='documentos/certidoes/'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='comprovante_residencia',
            field=models.FileField(upload_to='documentos/comprovantes_residencia/'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='cpf_responsavel',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='documento_responsavel',
            field=models.FileField(upload_to='documentos/documentos_responsavel/'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='endereco_bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='endereco_cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='endereco_numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='endereco_rua',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='endereco_uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
