# Generated by Django 5.2.2 on 2025-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0004_alter_matricula_certidao_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20),
        ),
    ]
