# Generated by Django 5.2.2 on 2025-06-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0005_alter_matricula_data_nascimento_alter_matricula_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('analise', 'Em análise'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='analise', max_length=10),
        ),
    ]
